[package]
name = "erised-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
darling = "0.14.4"
proc-macro2 = "1.0.50"
quote = "1.0.23"
syn = { version = "1.0.107", features = ["visit", "visit-mut"]}


